import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";
import SideNav from "@/components/root/side-nav";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Daniel O. Johnson",
  description: "Generated by bean water",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className="bg-black">
        <div className="h-screen w-screen">
          <SideNav>{children}</SideNav>
        </div>
      </body>
    </html>
  );
}
