import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { AuroraHero } from "@/components/root/aurora-hero";

export const metadata: Metadata = {
  title: "Daniel O. Johnson",
  description: "Generated by bean water",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className="bg-black">
        <AuroraHero>{children}</AuroraHero>
      </body>
    </html>
  );
}
